# Problem 2
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# 
# Author: Jose Manuel Martinez Salas

fib_list = [1,2]
max = 4000000 # 4 millions

while(fib_list[-1] < max):
    fib_list.append(fib_list[-1] + fib_list[-2])

print(sum([num for num in fib_list if (num % 2 == 0)]))